name: Kashi CI

on:
  workflow_call:
    inputs:
      test1:
        description: test arg
        required: true
        type: string
    secrets:
      test-secret:
        required: true
jobs:
    Devops:
        name: Devops Job
        runs-on: ubuntu-latest
        steps:
            - name: RUN TEST
              run: |
                mkdir secret-text
                echo ${{ secrets.test-secret }} > secret-text/mysecret.txt
            - name: archive OUTPUT
              uses: actions/upload-artifact@v4
              with:
                path: secret-text
                name: ${{ inputs.test1 }}
