name: Execute loop
description: Loop through 'x' range of numbers.

inputs:
  number:
    required: true
    description: specify the range
    type: number 

runs:
  using: composite

steps:
  - name: print echo 1
    run: echo "Hello ..step 1"
    shell: bash
  - name: print echo 2
    run: echo "Hello .. step 2"
    shell: bash
  - name: loop
    run: for ((i=1; i<${{ inputs.number }}; i++)); do echo $i; done
    shell: bash
