name: Kashi CI

on:
  workflow_call:
    inputs:
      test1:
        description: test arg
        required: true
        type: string
        # default: hind


# Let's consider a scenario where you are generating some artifacts in the calling workflow and say
# we have to generate pass some inputs to this called workflow. We need to pass the inputs because we don't
# want to hardcode the path and artifact name in the step. if you do so, this would not be reusable.
# Think of this reusable wokflow as function which accepts some params which needs to be passed from the calling workflow.

jobs:
    Devops:
        name: Devops Job
        runs-on: ubuntu-latest
        steps:
            - name: RUN TEST
              run: echo "Test ... ${{ inputs.test1 }}"
            - name: OUTPUT INFO
              run: echo "o/p -> test"
          
# IF input is not provided it will throw an err.
# The workflow is not valid. .github/workflows/build-flow.yml (Line: 19, Col: 11): 
# Input test1 is required, but not provided while calling.
