name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: ["main"]

  workflow_dispatch: null

env:
  KASHI_USERNAME: Hind
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: mine
        id: mine
        run: echoz "hind_username=maa" > $GITHUB_OUTPUT
      - name: text
        if: failure()
        run: echo ${{ steps.mine.outputs.hind_username }}
      - name: Rest
        if: failure()
        run: sleep 20
      - name: cancell flow
        if: cancelled()
        run: echo "Workflow cancelled post steps..."
