name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: ["main"]

  workflow_dispatch: null

jobs:
  break:
    name: Test containersiation
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: action/checkout@v3
      - name: Test env
        run: |
          pwd
      - name: composite execution
        uses: ./.github/workflows/composite/loop
        with:
          number: 20
