name: CI
on:
  push:
    branches: [ "main", "dev" ]

  workflow_dispatch: null

env:
  KASHI_USERNAME: Hind
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dev tests
        run: echo "dev"
      - name: Run a one-line script
        if: github.ref == 'refs/heads/main'
        run: echo "I am only run on master"

