name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: ["main"]

  workflow_dispatch: null

env:
  KASHI_USERNAME: Hind
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dev tests
        run: echo ${{ github.ref }}
      - name: Run a one-line script
        if: github.ref == 'refs/pull/*'
        run: echo "I am only run on master"

