name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: ["main"]

  workflow_dispatch: null

jobs:
  break:
    name: Test containersiation
    runs-on: ubuntu-latest
    container:
      image: nginx
    services:
      maa:
        image: nginx
    steps:
      - name: Test env
        run: |
          pwd
          echo "---------------------"
          cat /etc/os-release
          echo "---------------------"
          cd /etc/nginx
          ls
          cat /etc/resolv.conf
          ping -c 3 maa