name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch: null

env:
  KASHI_USERNAME: Hind
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        if: ${GITHUB_REF} == 'main'
        run: echo "I am only run on master"

