name: Kashi CI

on:
  workflow_call:
    # inputs:
    #   test1:
    #     description: test arg
    #     required: true
    #     type: string
    # secrets:
    #   test-secret:
    #     required: true
    outputs:
      result: 
        value: ${{ jobs.devops.outputs.custom }}
        description: the value


jobs:
    devops:
        name: Devops Job
        runs-on: ubuntu-latest
        outputs:
          custom: ${{ steps.print.outputs.app }}
        steps:
            - name: print out
              id: print
              run: echo "app=${{ secrets.KASHI_PASSWORD }}" > $GITHUB_OUTPUT
